# Copyright 2023 The MathWorks, Inc

# Composite Action to Build and Publish in PyPi
name: Build and Publish in PyPi
inputs:
  pypi_token:
    description: 'PyPi API Token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Python build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
      shell: bash

    - name: Build Source and Binary wheel distributions
      run: python setup.py bdist_wheel sdist
      shell: bash

    - name: Publish to PyPI.
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        verbose: true
        password: ${{ inputs.pypi_token }}
        repository_url: https://upload.pypi.org/legacy/