# Copyright 2020-2023 The MathWorks, Inc

# Workflow to release to PyPi
name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  build_and_publish_pypi:
    # windows container is not required here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.sha}}

      - name: Build and Publish in PyPi
        uses: ./.github/actions/build_and_publish_pypi
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}